.pragma library

// Generated by omarchy-style from ~/.config/omarchy/style-tokens.toml.
// Do not edit: the next sync overwrites this file.

var elevOverlayAlpha = 0.5
var elevOverlayBlur = 38
var elevOverlayY = 14
var elevPopupAlpha = 0.35
var elevPopupBlur = 18
var elevPopupY = 6
var motionFast = 150
var motionInstant = 90
var motionNormal = 260
var motionRise = 8
var motionScaleFrom = 0.965
var ruleAlpha = 0.16
var scrimAlpha = 0.3
