
# NVIDIA (Turing+ with GSP firmware)
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Steam: fix WebView rendering on NVIDIA Wayland
env = STEAM_DISABLE_GPU_RASTERIZATION,1
# Steam: use evdev instead of HIDAPI for PS4 controller (hid-playstation compatibility)
env = SDL_JOYSTICK_HIDAPI_PS4,0

# Screenshots
env = OMARCHY_SCREENSHOT_DIR,/home/marcos/Pictures/Screenshots

# Cursor
env = XCURSOR_THEME,Nordzy-cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Nordzy-cursors
env = HYPRCURSOR_SIZE,24
